[CombatSpeed]
; Minimum selectable combat speed multiplier...
Min=0.25
; Maximum selectable combat speed multiplier...
Max=8.00
; Amount we increment between each option...
Step=0.25
; Preset hotkeys for 1-8 on the keyboard...
Preset1=1.00
Preset2=2.00
Preset3=3.00
Preset4=4.00
Preset5=5.00
Preset6=6.00
Preset7=7.00
Preset8=8.00

[Hotkeys]
; You can use single letters/numbers, named keys, function keys, or decimal/hex virtual-key codes!
; Up to two comma-separated keys are supported per action!
; NOTE: Leave this value empty (or set it to NONE) (Example: Preset1= or Preset1=NONE) to disable the hotkey!
Decrease=OEM_MINUS,SUBTRACT
Increase=OEM_PLUS,ADD
Reset=0,NUMPAD0
Preset1=1,NUMPAD1
Preset2=2,NUMPAD2
Preset3=3,NUMPAD3
Preset4=4,NUMPAD4
Preset5=5,NUMPAD5
Preset6=6,NUMPAD6
Preset7=7,NUMPAD7
Preset8=8,NUMPAD8