[CombatSpeed]
; Minimum selectable combat speed multiplier...
Min=0.25
; Maximum selectable combat speed multiplier...
Max=8.00
; Amount we increment between each option...
Step=0.25
; Preset hotkeys for 1-8 on the keyboard...
Preset1=1.00
Preset2=2.00
Preset3=3.00
Preset4=4.00
Preset5=5.00
Preset6=6.00
Preset7=7.00
Preset8=8.00